CREATE TABLE FAMILIARES (
ID_FAMILIAR INT IDENTITY NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
APODO VARCHAR(50) NOT NULL
);

INSERT INTO FAMILIARES (NOMBRE, APELLIDO, APODO) VALUES (?,?,?);
