CREATE TABLE FAMILIARES (
ID_FAMILIAR INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
APODO VARCHAR(50) NOT NULL
);

INSERT INTO FAMILIARES (ID_FAMILIAR, NOMBRE, APELLIDO, APODO) VALUES (1,'FERNANDA','HERNANDEZ','PRINCESA');
INSERT INTO FAMILIARES (ID_FAMILIAR, NOMBRE, APELLIDO, APODO) VALUES (2,'JACQUELINE','GALEANA','CHINA');
INSERT INTO FAMILIARES (ID_FAMILIAR, NOMBRE, APELLIDO, APODO) VALUES (3,'LUZ','CONO','FIONA');
INSERT INTO FAMILIARES (ID_FAMILIAR, NOMBRE, APELLIDO, APODO) VALUES (4,'KENIA','HERNANDEZ','MUÑE');
INSERT INTO FAMILIARES (ID_FAMILIAR, NOMBRE, APELLIDO, APODO) VALUES (5,'JUAN','HERNANDEZ','SHREK');

